#! /bin/sh

bspc monitor -d I II III IV V

bspc config border_width          1
bspc config window_gap            4
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc rule -a Gimp follow=on floating=on

/home/zander/.config/bspwm/panel/panel &
