#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
conky -c $HOME/.config/panel/panel_conky > "$PANEL_FIFO" &

. panel_colors

cat "$PANEL_FIFO" | panel_bar | bar -f "-zevv-peep-medium-r-normal--16-140-75-75-c-80-iso8859-1","-xos4-terminus-medium-r-normal--12-120-72-72-c-60-iso10646-1" -g x$PANEL_HEIGHT -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
